articles/urls.py
from django.urls import path
from articles.views import List, Detail, New, Modify, Remove

app_name = "articles"

urlpatterns = [
    path("", List.as_view(), name="list"),
    path("<int:pk>/", Detail.as_view(), name="detail"),
    path("write/", New.as_view(), name="new"),
    path("update/<int:pk>", Modify.as_view(), name="modify"),
    path("delete/<int:pk>", Remove.as_view(), name="remove")
]

core/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import IndexView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", IndexView.as_view(), name="index"),
    path("users/", include("users.urls")),
    path("blog/", include("articles.urls")),
    path("tinymce/", include("tinymce.urls")),
]

users/urls.py
from django.urls import path
from users.views import SigninView, SignupView, SignoutView

app_name = "users"

urlpatterns = [
    path("signin/", SigninView.as_view(), name="signin"),
    path("signup/", SignupView.as_view(), name="signup"),
    path("signout/", SignoutView.as_view(), name="signout"),
]

articles/models.py
import tinymce.models
from django.db import models
from users.models import User
from django.utils.translation import gettext_lazy as lazy


class Article(models.Model):
    """Model of articles"""

    title = models.CharField(max_length=255)

    # rich text editor HTML Field
    content = tinymce.models.HTMLField()

    created_at = models.DateTimeField(verbose_name="created at", auto_now_add=True)

    modified_at = models.DateTimeField(verbose_name="modified at", auto_now=True)

    # Article }o--|| User
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    view_count = models.PositiveIntegerField(verbose_name="view count", default=0)

    likes = models.ManyToManyField(User, related_name="likes", blank=True)

    class Category(models.TextChoices):
        TECH = "TECH", lazy("기술")
        FOOD = 'FOOD', lazy("음식")
        MUSIC = "MUSIC", lazy("음악")
        EMOTIONS = "EMOTIONS", lazy("감정")
        SCIENCE = "SCIENCE", lazy("과학")
        ARTS = "ARTS", lazy("예술")
        ANNOUNCE = "ANNOUNCE", lazy("공지")
        MISC = "MISC", lazy("기타")

    # Article }o--|| Category
    category = models.CharField(max_length=10, choices=Category.choices, default=Category.MISC)

users/models.py
from typing import Optional
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager,
    AbstractBaseUser,
    PermissionsMixin,
)


class UserManager(BaseUserManager):
    def __create_user(self, email, nickname=None, password=None):
        """avoid duplication"""
        if not email:
            raise ValueError("The Email field must be set! 💀")

        user = self.model(email=self.normalize_email(email), nickname=nickname)
        user.set_password(password)

        return user

    def create_user(self, email, nickname=None, password=None):
        """Create and save User with given parameters"""
        user = self.__create_user(email, nickname=nickname, password=password)
        user.save(using=self._db)

        return user

    def create_superuser(self, email, nickname=None, password=None):
        """Create and save Superuser with given parameters"""
        user = self.__create_user(email, nickname=nickname, password=password)
        user.is_superuser = True
        user.is_staff = True

        user.save(using=self._db)

        return user


class User(AbstractBaseUser, PermissionsMixin):
    """Custom User Model"""

    email = models.EmailField(verbose_name="email address", max_length=255, unique=True)
    nickname = models.CharField(max_length=255)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["nickname"]

    def __str__(self):
        return str(self.nickname)

    def has_perm(self, perm: str, obj=None) -> bool:
        return super().has_perm(perm, obj)

    def has_module_perms(self, app_label: str) -> bool:
        return super().has_module_perms(app_label)

articles/forms.py
from django import forms
from tinymce.widgets import TinyMCE
from articles.models import Article


class ArticleForm(forms.ModelForm):
    """TinyMCE widget"""

    class Meta:
        model = Article
        widgets = {"content": TinyMCE(attrs={"cols": 80, "rows": 30})}
        fields = ["title", "content", "category"]

articles/views.py
from typing import Any, Dict
from django.forms.models import BaseModelForm
from django.http import HttpRequest, HttpResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from articles.models import Article
from articles.forms import ArticleForm


class List(ListView):
    """전체 리스트를 보여주기"""

    template_name = "list.html"
    model = Article
    queryset = Article.objects.all().order_by("-modified_at")
    paginate_by = 2


class Detail(DetailView):
    """상세 페이지"""

    template_name = "view.html"
    model = Article


class New(LoginRequiredMixin, CreateView):
    """Create new article"""

    model = Article
    template_name = "write.html"
    form_class = ArticleForm
    success_url = reverse_lazy("articles:list")
    queryset = model.objects.all()

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        """form.is_valid()가 통과하면 무조건 실행되는 메서드, save 하기 전에
        여기에 `author` 정보를 추가해야 한다."""
        form.instance.author = self.request.user

        return super().form_valid(form)


class Modify(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """글 수정"""

    model = Article
    template_name = "update.html"
    form_class = ArticleForm
    success_url = reverse_lazy("articles:list")
    queryset = model.objects.all()

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        """form.is_valid()가 통과하면 무조건 실행되는 메서드, save 하기 전에
        여기에 `author` 정보를 추가해야 한다."""
        form.instance.author = self.request.user

        return super().form_valid(form)

    def test_func(self) -> bool | None:
        """author와 request 유저와 일치하여야 함."""
        # TODO - impl
        return True


class Remove(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """글 삭제 확인페이지.
    문서에 따르면 요청 메서드가 POST일 경우에만 삭제를 수행한다고 하니 참고바람."""

    model = Article
    template_name = "delete.html"
    success_url = reverse_lazy("articles:list")
    queryset = model.objects.all()

    def test_func(self) -> bool | None:
        """author와 request 유저와 일치하여야 함."""
        # TODO - impl
        return True

core/views.py
from django.views.generic.base import TemplateView


class IndexView(TemplateView):
    template_name = "index.html"

users/views.py
from typing import Any
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView
from users.models import User


class SigninView(LoginView):
    template_name = "login.html"


class SignoutView(LoginRequiredMixin, LogoutView):
    template_name = "logout.html"


class SignupView(CreateView):
    template_name = "join.html"
    model = User
    fields = "__all__"

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko-KR">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title>
    {% block title %}
    {% endblock title %}
  </title>

  <link rel="stylesheet" href="{% static 'css/bootstrap-5.3.0-dist/bootstrap.css' %}" />
  <link rel="icon" type="image/png" href="{% static 'favicon/favicon-32x32.png'%}" sizes="32x32" />
  <link rel="icon" type="image/png" href="{% static 'favicon/favicon-16x16.png'%}" sizes="16x16" />

  <script src="{% static 'js/bootstrap-5.3.0-dist/bootstrap.js' %}"></script>
  
  {% block head %}
  {% endblock head %}

  {% block stylesheet %}
  {% endblock stylesheet %}

  {% block script %}
  {% endblock script %}
</head>

<body>

  {% include 'nav.html' %}

  {% block body %}
  {% endblock body %}

  {% include 'footer.html' %}
</body>

</html>

templates/delete.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
confirm deletion
{% endblock title %}

{% block body %}
<div class="container p-3 mt-3 bg-light border rounded">
    <a href="{% url 'articles:detail' object.id %}" class="btn btn-outline-secondary">
        <img width="20px" height="20px" src="{% static 'img/prev.png' %}" alt="이전 페이지" />
    </a>
    <a href="#" class="page-link"></a>
    <div class="row">
        <div class="mx-md-auto mx-3 col-11 mt-3">
            <h1>게시글 삭제</h1>
            <h3><strong class="text-muted font-weight-bold">{{ object.title|truncatechars:15 }}</strong> 을 정말로 삭제하시겠습니까?</h3>
        </div>
        <form method="post">
            {% csrf_token %}
            <button class="btn btn-danger mt-3" type="submit">확인</button>
        </form>
    </div>
</div>

{% endblock body %}

templates/footer.html
<footer class="text-center p-4 mt-5 bg-light text-muted">
    Copyright 2023. <a class="text-black" href="https://github.com/ChoiWheatley">ChoiWheatley </a> rights reserved.
</footer>

templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block body %}
<div class="container p-3 mt-3 bg-light border rounded">
  <div class="row">
    <h2 class="mx-md-auto mx-3 col-11 mt-3">Welcome!</h2>
    <a class="btn btn-lg col-3 btn-primary m-3" href="{% url 'articles:list' %}">전체 글</a>
  </div>
</div>
{% endblock body %}

templates/join.html
{% extends 'base.html' %}


{% block body %}
<div class="main">
    <div class="container">
      <h2 class="title">회원가입</h2>
      <p class="description">
        원활한 서비스를 이용을 위해 회원가입을 해주세요
      </p>

      <form class="login">
        <div>
          <label class="label-width" for="user-id">아이디</label>
          <input type="text" id="user-id" name="userId" required>
        </div>
        <div>
          <label class="label-width" for="user-email">이메일</label>
          <input type="email" id="user-email" name="userEmail" required>
        </div>
        <div>
          <label class="label-width" for="user-pw">비밀번호</label>
          <input type="password" id="user-pw" name="userPw" required>
        </div>
        <div>
          <label class="label-width" for="user-nick">닉네임</label>
          <input type="text" id="user-nick" name="userNick" required>
        </div>
        <fieldset class="field">
          <legend>성별</legend>
          <ul>
            <li>
              <input name="gender" type="radio" id="gender1">
              <label for="gender1">남성</label>
            </li>
            <li>
              <input name="gender" type="radio" id="gender2">
              <label for="gender2">여성</label>
            </li>
            <li>
              <input name="gender" type="radio" id="gender3">
              <label for="gender3">선택 안함</label>
            </li>
          </ul>
        </fieldset>
        <fieldset class="field">
          <legend>사용 기술</legend>
          <ul>
            <li>
              <input name="html" type="checkbox" id="tech1">
              <label for="tech1">HTML</label>
            </li>
            <li>
              <input name="css" type="checkbox" id="tech2">
              <label for="tech2">CSS</label>
            </li>
            <li>
              <input name="js" type="checkbox" id="tech3">
              <label for="tech3">JavaScript</label>
            </li>
            <li>
              <input name="python" type="checkbox" id="tech4">
              <label for="tech4">Python</label>
            </li>
            <li>
              <input name="django" type="checkbox" id="tech5">
              <label for="tech5">Django</label>
            </li>
            <li>
              <input name="github" type="checkbox" id="tech6">
              <label for="tech6">GitHub</label>
            </li>
            <li>
              <input name="sql" type="checkbox" id="tech7">
              <label for="tech7">PostgreSQL</label>
            </li>
          </ul>
        </fieldset>

        <button class="submit-button" type="submit">회원가입</button>
      </form>
    </div>
  </div>
{% endblock body %}

templates/list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
전체 글 목록
{% endblock title %}

{% block body %}
<div class="container">
    <h2 class="fw-bolder">게시판</h2>

    <div class="text-muted">
        <p><strong>{{ page_obj.paginator.count }}개</strong>의 게시글이 있습니다.</p>

        <form>
            <div class="mx-md-auto p-2 mt-5 mb-5 bg-light form-group">
                <label for="category" class="text-muted">카테고리</label>
                <select class="form-select" id="category">
                    <option>전체</option>
                    <option>공지사항</option>
                    <option>일반</option>
                </select>

                <label for="sort" class="text-muted">정렬</label>
                <select class="form-select" id="sort">
                    <option>조회순</option>
                    <option>최신순</option>
                </select>

                <label for="search" class="text-muted">검색</label>
                <input id="search" type="search" class="form-control" placeholder="검색어를 입력해주세요" />
                <button class="d-inline-block float-end btn btn-light" type="submit">
                    <img class="rounded-circle" width="30px" height="30px" src="{% static 'img/icon-search.png' %}" alt="검색" />
                </button>
            </div>
        </form>
    </div>

    <!-- 게시판 리스트 -->
    <table class="table">
        <thead>
            <tr>
                <th>
                    <input type="checkbox" id="all-article" />
                    <!-- <label for="all-article">페이지 전체 게시글 선택</label> -->
                </th>
                <th>번호</th>
                <th>제목</th>
                <th>작성자</th>
                <th>작성일</th>
                <th>조회수</th>
            </tr>
        </thead>
        <tbody>

            {% if object_list|length == 0 %}

            <td class="nodata" colspan="5">등록된 게시물이 없습니다.</td>

            {% else %}


            {% for object in object_list %}
            <tr>
                <td><input type="checkbox" id="check{{object.id}}" /></td>
                <td>{{object.id}}</td>
                <td>
                    <a href="{% url 'articles:detail' object.id %}">
                        {{object.title|truncatewords:15|safe}}
                    </a>
                </td>
                <td> {{ object.author.nickname }} </td>
                <td> {{ object.created_at|date:"Y.m.d" }} </td>
                <td> {{ object.view_count }} </td>
            </tr>
            {% endfor %}


            {% endif %}

        </tbody>
    </table>

    <div class="board-bottom">
        <!-- 페이지 -->
        <ul class="pagination">
            <div class="mx-auto d-flex flex-row">

                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a href="?page=1" class="page-link">
                        <img width="20px" height="20px" src="{% static 'img/first.png' %}" alt="처음 페이지" />
                    </a>
                </li>
                <li class="page-item">
                    <a href="?page={{ page_obj.previous_page_number }}" class="page-link">
                        <img width="20px" height="20px" src="{% static 'img/prev.png' %}" alt="이전 페이지" />
                    </a>
                </li>

                {% else %}

                <li class="page-item">
                    <a href="#" class="page-link disabled">
                        <img width="20px" height="20px" src="{% static 'img/first.png' %}" alt="처음 페이지" />
                    </a>
                </li>
                <li class="page-item">
                    <a href="#" class="page-link disabled">
                        <img width="20px" height="20px" src="{% static 'img/prev.png' %}" alt="이전 페이지" />
                    </a>
                </li>

                {% endif %}

                <li class="page-item">
                    <a href="#" class="page-link">
                        {{page_obj.number}} / {{page_obj.paginator.num_pages}}
                    </a>
                </li>

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a href="?page={{ page_obj.next_page_number }}" class="page-link">
                        <img width="20px" height="20px" src="{% static 'img/next.png' %}" alt="첫번째 페이지" />
                    </a>
                </li>
                <li class="page-item">
                    <a href="?page={{ page_obj.paginator.num_pages }}" class="page-link">
                        <img width="20px" height="20px" src="{% static 'img/last.png' %}" alt="이전 페이지" />
                    </a>
                </li>
                {% else %}
                <li class="page-item">
                    <a href="#" class="page-link disabled">
                        <img width="20px" height="20px" src="{% static 'img/next.png' %}" alt="첫번째 페이지" />
                    </a>
                </li>
                <li class="page-item">
                    <a href="#" class="page-link disabled">
                        <img width="20px" height="20px" src="{% static 'img/last.png' %}" alt="이전 페이지" />
                    </a>
                </li>
                {% endif %}

            </div>
        </ul>
        <div class="btn-group">
            <button class="btn btn-outline-primary">선택삭제</button>
            <a href="{% url 'articles:new' %}" class="btn btn-outline-primary">작성</a>
        </div>
    </div>
</div>
{% endblock body %}

templates/login.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block body %}
<div class="main">
  <div class="container">
    <h2 class="title">로그인</h2>
    <p class="description">아이디와 비밀번호를 입력하고 로그인하세요</p>

    <div class="col-11 col-md-5 mx-auto mt-5">
      <form action="{% url 'users:signin' %}" method="post">

        {% csrf_token %}

        {{ form|crispy }}

        <button class="btn btn-primary" type="submit">로그인</button>
      </form>

      <div class="pt-3">
        <small class="text-muted">
          아이디가 없나요?
          <a href="{% url 'users:signup' %}" class="ml-2">회원가입</a>
        </small>
      </div>
    </div>
  </div>
</div>
{% endblock body %}

templates/logout.html
{% extends 'base.html' %}


{% block body %}
<div class="main">
    <div class="container bg-light border rounded">
        <div class="mx-md-auto col-11 m-3">
            <h2>로그아웃 되었습니다.</h2>
        </div>
        <div class="btn-group col-11 m-3">
            <a class="btn btn-primary m-1" href="{% url 'index' %}">main</a>
            <a class="btn btn-primary m-1" href="{% url 'users:signin' %}">로그인</a>
            <a class="btn btn-primary m-1" href="{% url 'users:signup' %}">회원가입</a>
        </div>
    </div>
</div>
{% endblock body %}

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
    <div class="container">
        <h1><a class="navbar-brand" href="{% url 'index' %}">ormi-project-2</a></h1>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
            aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-md-auto">
                {% if request.user.is_authenticated %}
                <a class="nav-link" href="{% url 'users:signout' %}">로그아웃</a>
                {% else %}
                <a class="nav-link" href="{% url 'users:signin' %}">로그인</a>
                <a class="nav-link" href="{% url 'users:signup' %}">회원가입</a>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/update.html
{% extends 'base.html' %}

{% load static %}

{% block head %}
  {{ form.media }}
{% endblock head %}

{% block title %}
글쓰기
{% endblock title %}

{% block body %}
<div class="main">
  <!-- 글쓰기 페이지 -->
  <h2 class="main-title">글쓰기</h2>
  <p class="main-desc">내용을 입력 해주세요.</p>

  {{ form.non_field_errors }}

  <form action="{% url 'articles:modify' object.id %}" method="post">

    {% csrf_token %}

    <table class="table write">
      <colgroup>
        <col style="width: 120px">
        <col>
      </colgroup>
      <tbody>
        <tr>
          <th><label for="category">카테고리</label></th>
          <td>
            {{ form.category.errors }}
            {{ form.category }}
          </td>
        </tr>
        <tr>
          <th><label for="board-title">제목</label></th>
          <td>
            {{ form.title.errors }}
            {{ form.title }}
          </td>
        </tr>
        <tr>
          <th><label for="board-content">내용</label></th>
          <td>
            {{ form.content.errors }}
            {{ form.content }}
          </td>
        </tr>
      </tbody>
    </table>
    <div class="btn-group">
      <a href="{% url 'articles:list' %}" class="btn">목록</a>
      <button type="reset" class="btn">초기화</button>
      <button type="submit" class="btn">작성</button>
    </div>
  </form>

  <!--  //글쓰기 페이지 -->
</div>
{% endblock body %}

<!DOCTYPE html>
<html lang="ko-KR">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>글쓰기</title>
  <link rel="stylesheet" href="./css/common.css">
  <link rel="stylesheet" href="./css/table.css">
  <link rel="stylesheet" href="./css/write.css">

</head>

templates/view.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
글 조회
{% endblock title %}

{% block body %}

<div class="container">

  <a href="{% url 'articles:list' %}" class="btn btn-outline-secondary">
    <img width="20px" height="20px" src="{% static 'img/prev.png' %}" alt="이전 페이지" />
  </a>
  <div class="view">
    <div class="view-header">
      <h1>{{object.title}}</h1>
      <div class="view-info">
        <p>작성자: {{object.author.nickname}}</p>
        <p>작성일: {{object.created_at|date:"Y.m.d"}}</p>
        <p>조회수: {{object.view_count}}</p>
      </div>
    </div>

    <div class="view-content">
      {{object.content|safe}}
    </div>

  </div>
  <div class="btn-group">
    <a href="{% url 'articles:list' %}" class="btn btn-outline-secondary">목록</a>
    <a href="{% url 'articles:modify' object.id %}" class="btn btn-outline-secondary">수정</a>
    <a href="{% url 'articles:remove' object.id %}" class="btn btn-outline-danger">삭제</a>
  </div>

</div>

{% endblock body %}

templates/write.html
{% extends 'base.html' %}

{% load static %}


{% block title %}
글쓰기
{% endblock title %}


{% block body %}
<div class="main">
  <!-- 글쓰기 페이지 -->
  <h2 class="main-title">글쓰기</h2>
  <p class="main-desc">내용을 입력 해주세요.</p>

  {{ form.non_field_errors }}

  <form action="{% url 'articles:new' %}" method="post">

    {% csrf_token %}

    <table class="table write">
      <colgroup>
        <col style="width: 120px">
        <col>
      </colgroup>
      <tbody>
        <tr>
          <th><label for="category">카테고리</label></th>
          <td>
            {{ form.category.errors }}
            {{ form.category }}
          </td>
        </tr>
        <tr>
          <th><label for="board-title">제목</label></th>
          <td>
            {{ form.title.errors }}
            {{ form.title }}
          </td>
        </tr>
        <tr>
          <th><label for="board-content">내용</label></th>
          <td>
            {{ form.content.errors }}
            {{ form.content }}
          </td>
        </tr>
      </tbody>
    </table>
    <div class="btn-group">
      <a href="./index.html" class="btn">목록</a>
      <button type="reset" class="btn">초기화</button>
      <button type="submit" class="btn">작성</button>
    </div>
  </form>

  <!--  //글쓰기 페이지 -->
</div>
{% endblock body %}

<!DOCTYPE html>
<html lang="ko-KR">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>글쓰기</title>
  <link rel="stylesheet" href="./css/common.css">
  <link rel="stylesheet" href="./css/table.css">
  <link rel="stylesheet" href="./css/write.css">

</head>